/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package alex.oopsalestrackinggui;

/**
 *
 * @author Alex Resurreccion
 */
public class OOPSalesTrackingGUI extends javax.swing.JFrame {

    /**
     * Creates new form OOPSalesTrackingGUI
     */
    public OOPSalesTrackingGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jHomePagePanel = new javax.swing.JPanel();
        jLogoLabel = new javax.swing.JLabel();
        jLogoPanel = new javax.swing.JPanel();
        jWelcomeUserLabel = new javax.swing.JLabel();
        jLogOutButton = new javax.swing.JButton();
        jSalesTrackingButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jHomePagePanel.setBackground(new java.awt.Color(0, 0, 102));

        jLogoLabel.setBackground(new java.awt.Color(255, 255, 255));
        jLogoLabel.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLogoLabel.setForeground(new java.awt.Color(255, 255, 255));
        jLogoLabel.setText("LEXSmart Solutions");

        jLogoPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jLogoPanelLayout = new javax.swing.GroupLayout(jLogoPanel);
        jLogoPanel.setLayout(jLogoPanelLayout);
        jLogoPanelLayout.setHorizontalGroup(
            jLogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 188, Short.MAX_VALUE)
        );
        jLogoPanelLayout.setVerticalGroup(
            jLogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jWelcomeUserLabel.setBackground(new java.awt.Color(204, 204, 204));
        jWelcomeUserLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jWelcomeUserLabel.setForeground(new java.awt.Color(255, 255, 255));
        jWelcomeUserLabel.setText("Welcome Back user!");

        jLogOutButton.setText("Log out");
        jLogOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLogOutButtonActionPerformed(evt);
            }
        });

        jSalesTrackingButton.setText("Sales Tracking");
        jSalesTrackingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSalesTrackingButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jHomePagePanelLayout = new javax.swing.GroupLayout(jHomePagePanel);
        jHomePagePanel.setLayout(jHomePagePanelLayout);
        jHomePagePanelLayout.setHorizontalGroup(
            jHomePagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jHomePagePanelLayout.createSequentialGroup()
                .addGap(0, 153, Short.MAX_VALUE)
                .addComponent(jSalesTrackingButton)
                .addGap(94, 94, 94)
                .addComponent(jLogOutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(145, 145, 145))
            .addGroup(jHomePagePanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jHomePagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLogoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLogoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jHomePagePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jWelcomeUserLabel)
                .addGap(233, 233, 233))
        );
        jHomePagePanelLayout.setVerticalGroup(
            jHomePagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jHomePagePanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLogoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLogoLabel)
                .addGap(40, 40, 40)
                .addComponent(jWelcomeUserLabel)
                .addGap(78, 78, 78)
                .addGroup(jHomePagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSalesTrackingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLogOutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(114, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jHomePagePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jHomePagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLogOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLogOutButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLogOutButtonActionPerformed

    private void jSalesTrackingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSalesTrackingButtonActionPerformed
       SalesCalculation sales = new SalesCalculation();
       sales.setVisible(true);
       
       dispose();
    }//GEN-LAST:event_jSalesTrackingButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OOPSalesTrackingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OOPSalesTrackingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OOPSalesTrackingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OOPSalesTrackingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OOPSalesTrackingGUI().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jHomePagePanel;
    private javax.swing.JButton jLogOutButton;
    private javax.swing.JLabel jLogoLabel;
    private javax.swing.JPanel jLogoPanel;
    private javax.swing.JButton jSalesTrackingButton;
    private javax.swing.JLabel jWelcomeUserLabel;
    // End of variables declaration//GEN-END:variables
}
