/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package alex.oopsalestrackinggui;

import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author Alex Resurreccion
 */
public class SalesCalculation extends javax.swing.JFrame {

    /**
     * Creates new form SalesCalculation
     */
    public SalesCalculation() {
        initComponents();
        String currentDate = new SimpleDateFormat("MM/dd/yyyy").format(new Date());
        jPhoneDateTextField.setText(currentDate);
        jRepairDateValue.setText(currentDate);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSalesTrackingPanel = new javax.swing.JPanel();
        jLogoLabel = new javax.swing.JLabel();
        jLogoPanel = new javax.swing.JPanel();
        jCalculateSaleskButton = new javax.swing.JButton();
        jSalesReportLabel = new javax.swing.JLabel();
        jPhoneQtySoldLabel = new javax.swing.JLabel();
        jPhoneTotalSalesLabel = new javax.swing.JLabel();
        jPhoneTotalSalesValue = new javax.swing.JLabel();
        jPhoneSoldLabel = new javax.swing.JLabel();
        jPhoneDateLabel = new javax.swing.JLabel();
        jPhoneItemNameLabel = new javax.swing.JLabel();
        jPhonePriceLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jPhoneQtySoldTextField = new javax.swing.JTextField();
        jPhoneDateTextField = new javax.swing.JTextField();
        jPhoneItemNameTextField = new javax.swing.JTextField();
        jPhonePriceTextField = new javax.swing.JTextField();
        jRepairLabel = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jRepairDateLabel = new javax.swing.JLabel();
        jRepairItemNameLabel = new javax.swing.JLabel();
        jRepairPriceLabel = new javax.swing.JLabel();
        jRepairNumberHours = new javax.swing.JLabel();
        jRepairDateValue = new javax.swing.JTextField();
        jRepairItemValue = new javax.swing.JTextField();
        jRepairPriceValue = new javax.swing.JTextField();
        jRepairNumberHoursValue = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jRepairTotalSales = new javax.swing.JLabel();
        jRepairTotalSalesValue = new javax.swing.JLabel();
        jBackButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 400));
        setResizable(false);

        jSalesTrackingPanel.setBackground(new java.awt.Color(0, 0, 102));
        jSalesTrackingPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLogoLabel.setBackground(new java.awt.Color(255, 255, 255));
        jLogoLabel.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLogoLabel.setForeground(new java.awt.Color(255, 255, 255));
        jLogoLabel.setText("LEXSmart Solutions");
        jSalesTrackingPanel.add(jLogoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 130, 20));

        jLogoPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jLogoPanelLayout = new javax.swing.GroupLayout(jLogoPanel);
        jLogoPanel.setLayout(jLogoPanelLayout);
        jLogoPanelLayout.setHorizontalGroup(
            jLogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );
        jLogoPanelLayout.setVerticalGroup(
            jLogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jSalesTrackingPanel.add(jLogoPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 140, 20));

        jCalculateSaleskButton.setBackground(new java.awt.Color(0, 102, 0));
        jCalculateSaleskButton.setForeground(new java.awt.Color(255, 255, 255));
        jCalculateSaleskButton.setText("Calculate Sales");
        jCalculateSaleskButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCalculateSaleskButtonActionPerformed(evt);
            }
        });
        jSalesTrackingPanel.add(jCalculateSaleskButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 120, 31));

        jSalesReportLabel.setBackground(new java.awt.Color(204, 204, 204));
        jSalesReportLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jSalesReportLabel.setForeground(new java.awt.Color(255, 255, 255));
        jSalesReportLabel.setText("Sales Report");
        jSalesTrackingPanel.add(jSalesReportLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jPhoneQtySoldLabel.setBackground(new java.awt.Color(204, 204, 204));
        jPhoneQtySoldLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPhoneQtySoldLabel.setForeground(new java.awt.Color(255, 255, 255));
        jPhoneQtySoldLabel.setText("Quantity sold:");
        jSalesTrackingPanel.add(jPhoneQtySoldLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, -1, -1));

        jPhoneTotalSalesLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jPhoneTotalSalesLabel.setForeground(new java.awt.Color(255, 255, 255));
        jPhoneTotalSalesLabel.setText("Total sales:");
        jSalesTrackingPanel.add(jPhoneTotalSalesLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, 30));

        jPhoneTotalSalesValue.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jPhoneTotalSalesValue.setForeground(new java.awt.Color(255, 255, 255));
        jPhoneTotalSalesValue.setText("₱0,000.00");
        jPhoneTotalSalesValue.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));
        jSalesTrackingPanel.add(jPhoneTotalSalesValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 150, 30));

        jPhoneSoldLabel.setBackground(new java.awt.Color(204, 204, 204));
        jPhoneSoldLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPhoneSoldLabel.setForeground(new java.awt.Color(255, 255, 255));
        jPhoneSoldLabel.setText("Phones sold");
        jSalesTrackingPanel.add(jPhoneSoldLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        jPhoneDateLabel.setBackground(new java.awt.Color(204, 204, 204));
        jPhoneDateLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPhoneDateLabel.setForeground(new java.awt.Color(255, 255, 255));
        jPhoneDateLabel.setText("Date:");
        jSalesTrackingPanel.add(jPhoneDateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        jPhoneItemNameLabel.setBackground(new java.awt.Color(204, 204, 204));
        jPhoneItemNameLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPhoneItemNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        jPhoneItemNameLabel.setText("Item Name:");
        jSalesTrackingPanel.add(jPhoneItemNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, -1, -1));

        jPhonePriceLabel.setBackground(new java.awt.Color(204, 204, 204));
        jPhonePriceLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPhonePriceLabel.setForeground(new java.awt.Color(255, 255, 255));
        jPhonePriceLabel.setText("Price:");
        jSalesTrackingPanel.add(jPhonePriceLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, -1, -1));
        jSalesTrackingPanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 510, 10));

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jSalesTrackingPanel.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 510, 10));

        jPhoneQtySoldTextField.setForeground(new java.awt.Color(0, 0, 0));
        jPhoneQtySoldTextField.setText("10");
        jPhoneQtySoldTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPhoneQtySoldTextFieldActionPerformed(evt);
            }
        });
        jSalesTrackingPanel.add(jPhoneQtySoldTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 150, 90, -1));

        jPhoneDateTextField.setEditable(false);
        jPhoneDateTextField.setForeground(new java.awt.Color(0, 0, 0));
        jPhoneDateTextField.setText("01/01/2025");
        jPhoneDateTextField.setEnabled(false);
        jPhoneDateTextField.setFocusable(false);
        jPhoneDateTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPhoneDateTextFieldActionPerformed(evt);
            }
        });
        jSalesTrackingPanel.add(jPhoneDateTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 90, -1));

        jPhoneItemNameTextField.setForeground(new java.awt.Color(0, 0, 0));
        jPhoneItemNameTextField.setText("Phone");
        jPhoneItemNameTextField.setToolTipText("");
        jPhoneItemNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPhoneItemNameTextFieldActionPerformed(evt);
            }
        });
        jSalesTrackingPanel.add(jPhoneItemNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 90, -1));

        jPhonePriceTextField.setForeground(new java.awt.Color(0, 0, 0));
        jPhonePriceTextField.setText("500.00");
        jSalesTrackingPanel.add(jPhonePriceTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 90, -1));

        jRepairLabel.setBackground(new java.awt.Color(204, 204, 204));
        jRepairLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jRepairLabel.setForeground(new java.awt.Color(255, 255, 255));
        jRepairLabel.setText("Repair services");
        jSalesTrackingPanel.add(jRepairLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));
        jSalesTrackingPanel.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 510, 10));

        jRepairDateLabel.setBackground(new java.awt.Color(204, 204, 204));
        jRepairDateLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jRepairDateLabel.setForeground(new java.awt.Color(255, 255, 255));
        jRepairDateLabel.setText("Date:");
        jSalesTrackingPanel.add(jRepairDateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));

        jRepairItemNameLabel.setBackground(new java.awt.Color(204, 204, 204));
        jRepairItemNameLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jRepairItemNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        jRepairItemNameLabel.setText("Item Name:");
        jSalesTrackingPanel.add(jRepairItemNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, -1, -1));

        jRepairPriceLabel.setBackground(new java.awt.Color(204, 204, 204));
        jRepairPriceLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jRepairPriceLabel.setForeground(new java.awt.Color(255, 255, 255));
        jRepairPriceLabel.setText("Price per hour:");
        jSalesTrackingPanel.add(jRepairPriceLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, -1, -1));

        jRepairNumberHours.setBackground(new java.awt.Color(204, 204, 204));
        jRepairNumberHours.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jRepairNumberHours.setForeground(new java.awt.Color(255, 255, 255));
        jRepairNumberHours.setText("Number of hours:");
        jSalesTrackingPanel.add(jRepairNumberHours, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 250, -1, -1));

        jRepairDateValue.setEditable(false);
        jRepairDateValue.setForeground(new java.awt.Color(0, 0, 0));
        jRepairDateValue.setText("01/01/2025");
        jRepairDateValue.setEnabled(false);
        jRepairDateValue.setFocusable(false);
        jRepairDateValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRepairDateValueActionPerformed(evt);
            }
        });
        jSalesTrackingPanel.add(jRepairDateValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 90, -1));

        jRepairItemValue.setForeground(new java.awt.Color(0, 0, 0));
        jRepairItemValue.setText("Repair");
        jSalesTrackingPanel.add(jRepairItemValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 90, -1));

        jRepairPriceValue.setForeground(new java.awt.Color(0, 0, 0));
        jRepairPriceValue.setText("50.00");
        jSalesTrackingPanel.add(jRepairPriceValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, 90, -1));

        jRepairNumberHoursValue.setForeground(new java.awt.Color(0, 0, 0));
        jRepairNumberHoursValue.setText("5");
        jRepairNumberHoursValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRepairNumberHoursValueActionPerformed(evt);
            }
        });
        jSalesTrackingPanel.add(jRepairNumberHoursValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 270, 90, -1));
        jSalesTrackingPanel.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 510, 10));

        jRepairTotalSales.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jRepairTotalSales.setForeground(new java.awt.Color(255, 255, 255));
        jRepairTotalSales.setText("Total sales:");
        jSalesTrackingPanel.add(jRepairTotalSales, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, 30));

        jRepairTotalSalesValue.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jRepairTotalSalesValue.setForeground(new java.awt.Color(255, 255, 255));
        jRepairTotalSalesValue.setText("₱0,000.00");
        jRepairTotalSalesValue.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));
        jSalesTrackingPanel.add(jRepairTotalSalesValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 150, 30));

        jBackButton1.setBackground(new java.awt.Color(102, 102, 102));
        jBackButton1.setForeground(new java.awt.Color(255, 255, 255));
        jBackButton1.setText("Back");
        jBackButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBackButton1ActionPerformed(evt);
            }
        });
        jSalesTrackingPanel.add(jBackButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, 87, 31));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSalesTrackingPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSalesTrackingPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBackButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBackButton1ActionPerformed
        dispose();
        OOPSalesTrackingGUI salesTracking = new OOPSalesTrackingGUI();
        salesTracking.setVisible(true);
    }//GEN-LAST:event_jBackButton1ActionPerformed

    private void jRepairNumberHoursValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRepairNumberHoursValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRepairNumberHoursValueActionPerformed

    private void jRepairDateValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRepairDateValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRepairDateValueActionPerformed

    private void jPhoneDateTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPhoneDateTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPhoneDateTextFieldActionPerformed

    private void jPhoneQtySoldTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPhoneQtySoldTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPhoneQtySoldTextFieldActionPerformed

    private void jCalculateSaleskButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCalculateSaleskButtonActionPerformed
        String phone_name = jPhoneItemNameTextField.toString();
        double phone_price = Double.parseDouble(jPhonePriceTextField.getText());
        int phone_qty = Integer.parseInt(jPhoneQtySoldTextField.getText());
        Phone newPhone = new Phone(phone_name, phone_price, phone_qty);
        
        String repair_name = jRepairItemValue.toString();
        double repair_price = Double.parseDouble(jRepairPriceValue.getText());
        int number_hours = Integer.parseInt(jRepairNumberHoursValue.getText());
        
        RepairService newRepair = new RepairService(repair_name, repair_price, number_hours);
        jPhoneTotalSalesValue.setText(String.valueOf(newPhone.calculateTotalSales()));
        jRepairTotalSalesValue.setText(String.valueOf(newRepair.calculateTotalSales()));
    }//GEN-LAST:event_jCalculateSaleskButtonActionPerformed

    private void jPhoneItemNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPhoneItemNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPhoneItemNameTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SalesCalculation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SalesCalculation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SalesCalculation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SalesCalculation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SalesCalculation().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBackButton1;
    private javax.swing.JButton jCalculateSaleskButton;
    private javax.swing.JLabel jLogoLabel;
    private javax.swing.JPanel jLogoPanel;
    private javax.swing.JLabel jPhoneDateLabel;
    private javax.swing.JTextField jPhoneDateTextField;
    private javax.swing.JLabel jPhoneItemNameLabel;
    private javax.swing.JTextField jPhoneItemNameTextField;
    private javax.swing.JLabel jPhonePriceLabel;
    private javax.swing.JTextField jPhonePriceTextField;
    private javax.swing.JLabel jPhoneQtySoldLabel;
    private javax.swing.JTextField jPhoneQtySoldTextField;
    private javax.swing.JLabel jPhoneSoldLabel;
    private javax.swing.JLabel jPhoneTotalSalesLabel;
    private javax.swing.JLabel jPhoneTotalSalesValue;
    private javax.swing.JLabel jRepairDateLabel;
    private javax.swing.JTextField jRepairDateValue;
    private javax.swing.JLabel jRepairItemNameLabel;
    private javax.swing.JTextField jRepairItemValue;
    private javax.swing.JLabel jRepairLabel;
    private javax.swing.JLabel jRepairNumberHours;
    private javax.swing.JTextField jRepairNumberHoursValue;
    private javax.swing.JLabel jRepairPriceLabel;
    private javax.swing.JTextField jRepairPriceValue;
    private javax.swing.JLabel jRepairTotalSales;
    private javax.swing.JLabel jRepairTotalSalesValue;
    private javax.swing.JLabel jSalesReportLabel;
    private javax.swing.JPanel jSalesTrackingPanel;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    // End of variables declaration//GEN-END:variables
}

// Abstract class representing a generic item
abstract class Item {
    protected String name;
    protected double price;

    public Item(String name, double price) {
        this.name = name;
        this.price = price;
    }

    public String getName() {
        return name;
    }

    public double getPrice() {
        return price;
    }

    // Abstract method to calculate total sales
    public abstract double calculateTotalSales();
}

// Class for phone sales
class Phone extends Item {
    private int quantitySold;

    public Phone(String name, double price, int quantitySold) {
        super(name, price);
        this.quantitySold = quantitySold;
    }

    @Override
    public double calculateTotalSales() {
        return price * quantitySold;
    }
}

// Class for repair services
class RepairService extends Item {
    private int hoursWorked;

    public RepairService(String name, double pricePerHour, int hoursWorked) {
        super(name, pricePerHour);
        this.hoursWorked = hoursWorked;
    }

    @Override
    public double calculateTotalSales() {
        return price * hoursWorked;
    }
}
